name: Build

on:
  workflow_call:

  push:
    branches: [main]

  pull_request:
    branches: [main]

  release:
    types: [published]

  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-push-docker:
    uses: lameduse/actions/.github/workflows/build-push-docker.yaml@main
    secrets: inherit
  build-push-node:
    uses: lameduse/actions/.github/workflows/build-push-node.yaml@main
    secrets: inherit
  status-check:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - build-push-docker
      - build-push-node
    if: success()
    steps:
      - name: Final status check
        run: echo "All builds succeeded"
