name: Follow contributor (Issue Comment)

on:
  issue_comment:
    types: [created]

jobs:
  follow-user:
    uses: lameduse/actions/.github/workflows/follow-contributors.yaml@main
    secrets: inherit
