name: Lint

on:
  workflow_call:

  push:
    branches: [main]

  pull_request:
    branches: [main]

  release:
    types: [published]

  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: lameduse/actions/.github/workflows/lint.yml@main
    secrets: inherit
