branches:
  - main

plugins:
  - "@semantic-release/commit-analyzer"
    - releaseRules:
        - type: build
          release: patch
        - type: ci
          release: patch
        - type: chore
          release: patch
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
      changelogTitle: "# LaMeDuSe Change Log"
  - "@semantic-release/github"
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - package.json
      message: "chore(release): perform release ${nextRelease.version}"
