name: Build Push Docker

on:
  workflow_call:
    secrets:
      LAMEDUSE_REGISTRY_USERNAME:
        required: true
        description: 'Lameduse registry username'
      LAMEDUSE_REGISTRY_TOKEN:
        required: true
        description: 'Lameduse registry token'
    inputs:
      TARGET_DIR:
        required: false
        type: string
        description: 'Target directory in the registry'
        default: 'restricted'

    # vars:
    #   LAMEDUSE_REGISTRY:
    #     required: true
    #     description: 'Lameduse registry URL'

env:
  IMAGE_NAME: ${{ inputs.TARGET_DIR }}/${{ github.repository }}
  REGISTRY: ${{ vars.LAMEDUSE_REGISTRY }}

concurrency:
  group: build-push-docker-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.LAMEDUSE_REGISTRY_USERNAME }}
          password: ${{ secrets.LAMEDUSE_REGISTRY_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
